### ISSUE TITLE
kamanja update model java

### ISSUE THREAD

**Issue by ligadata-yousef** [LigaData/Kamanja#1039]
I am trying to update java model using this command:

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties update model java $KAMANJA_HOME/input/SampleApplications/metadata/model/HelloWorld.java DEPENDSON helloworldmodel TENANTID tenant1

but each time the below error raised:

ERROR [main] - COMPILER_PROXY: Unable to find at least one message in the Metadata for this model
ERROR [main] - COMPILER_PROXY: unable to determine model metadata information during AddModel.
com.ligadata.Exceptions.MsgCompilationFailedException: tenant1
        at com.ligadata.MetadataAPI.CompilerProxy.parseSourceForMetadata(CompilerProxy.scala:890) ~[KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.CompilerProxy.compileModelFromSource(CompilerProxy.scala:77) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.ModelUtils$.UpdateCustomModel(ModelUtils.scala:1385) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.ModelUtils$.UpdateModel(ModelUtils.scala:1136) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.MetadataAPIImpl$.UpdateModel(MetadataAPIImpl.scala:2330) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.Utility.ModelService$$anonfun$updateModeljava$1.apply(ModelService.scala:722) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.Utility.ModelService$$anonfun$updateModeljava$1.apply(ModelService.scala:719) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33) [ExtDependencyLibs2_2.10-1.4.0.jar:1.0]
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108) [ExtDependencyLibs2_2.10-1.4.0.jar:1.0]
        at com.ligadata.MetadataAPI.Utility.ModelService$.updateModeljava(ModelService.scala:719) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.route(StartMetadataAPI.scala:399) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI$.main(StartMetadataAPI.scala:239) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
        at com.ligadata.MetadataAPI.StartMetadataAPI.main(StartMetadataAPI.scala) [KamanjaInternalDeps_2.10-1.4.0.jar:0.1-SNAPSHOT]
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "\"UpdateModel(type = java)\"",
    "Result Data" : null,
    "Result Description" : "Error :com.ligadata.Exceptions.MsgCompilationFailedException: tenant1Failed to Update Model"
  }
}

while if you remove dependson the update command works:

$KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties update model java $KAMANJA_HOME/input/SampleApplications/metadata/model/HelloWorld.java TENANTID tenant1

Pick a Model Definition file(s) from below choices

[1]kamanja.helloworldmodel
[2]kamanja.copdriskassessment
[3]kamanja.copddataingest

Enter your choice:
1
Model config selected is kamanja.helloworldmodel
added manifest
adding: HelloWorldModel.java(in = 2874) (out= 1017)(deflated 64%)
adding: helloworldmodel.java(in = 2874) (out= 1017)(deflated 64%)
adding: com/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V0/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V0/HelloWorldModel.class(in = 1219) (out= 611)(deflated 49%)
adding: com/ligadata/kamanja/samples/models/V0/HelloWorldModel$HelloWorldModelFactory.class(in = 1016) (out= 487)(deflated 52%)
added manifest
adding: HelloWorldModel.java(in = 2874) (out= 1018)(deflated 64%)
adding: helloworldmodel.java(in = 2874) (out= 1018)(deflated 64%)
adding: com/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V2/(in = 0) (out= 0)(stored 0%)
adding: com/ligadata/kamanja/samples/models/V2/HelloWorldModel.class(in = 1219) (out= 611)(deflated 49%)
adding: com/ligadata/kamanja/samples/models/V2/HelloWorldModel$HelloWorldModelFactory.class(in = 1016) (out= 487)(deflated 52%)
Result: {
  "APIResults" : {
    "Status Code" : 0,
    "Function Name" : "AddModel",
    "Result Data" : null,
    "Result Description" : "Model Added Successfully:com.ligadata.kamanja.samples.models.helloworldmodel.000000000000000002"
  }
}

 note: first style of command (with dependson work with update scala model)

**Comment by ligadata-pokuri** [comment]
Hi dan, can you take a look at it?

**Comment by ligadata-dan** [comment]
@ligadata-yousef 

Please verify

**Comment by ligadata-yousef** [comment]
fixed

**Comment by aerndavid** [comment]
Still happens in 1.6 -

`# bash $KAMANJA_HOME/bin/kamanja $KAMANJA_HOME/config/MetadataAPIConfig.properties add model java $KAMANJA_HOME/input/SampleApplications/metadata/model/HelloWorld.java DEPENDSON helloworldmodel TENANTID tenant1
 WARN [main] - DATABASE_SCHEMA remains unset
 WARN [main] - DATABASE_LOCATION remains unset
 WARN [main] - MODEL_EXEC_LOG remains unset
 WARN [main] - DATABASE_HOST remains unset
 WARN [main] - ADAPTER_SPECIFIC_CONFIG remains unset
 WARN [main] - SSL_PASSWD remains unset
 WARN [main] - AUDIT_PARMS remains unset
 WARN [main] - GIT_ROOT remains unset
 WARN [main] - DATABASE remains unset
JAVA_HOME => /usr/java/jdk1.8
SECURITY_IMPL_CLASS => com.ligadata.Security.SimpleApacheShiroAdapter
JAR_PATHS => /usr/Kamanja_1.6.0_2.11/lib/system,/usr/Kamanja_1.6.0_2.11/lib/application
CONTAINER_FILES_DIR => /usr/Kamanja_1.6.0_2.11/input/SampleApplications/metadata/container/
SERVICE_PORT => 8081
SECURITY_IMPL_JAR => /usr/Kamanja_1.6.0_2.11/lib/system/simpleapacheshiroadapter_2.11-1.0.jar
ZOOKEEPER_CONNECT_STRING => localhost:2181
SCALA_HOME => /usr
SERVICE_HOST => localhost
ZK_SESSION_TIMEOUT_MS => 3000
TYPE_FILES_DIR => /usr/Kamanja_1.6.0_2.11/input/SampleApplications/metadata/type/
MODEL_EXEC_FLAG => false
DO_AUTH => NO
COMPILER_WORK_DIR => /usr/Kamanja_1.6.0_2.11/workingdir
SSL_CERTIFICATE => /usr/Kamanja_1.6.0_2.11/config/keystore.jks
API_LEADER_SELECTION_NODE_PATH => /kamanja
CONCEPT_FILES_DIR => /usr/Kamanja_1.6.0_2.11/input/SampleApplications/metadata/concept/
ROOT_DIR => /usr/Kamanja_1.6.0_2.11
MODEL_FILES_DIR => /usr/Kamanja_1.6.0_2.11/input/SampleApplications/metadata/model/
MESSAGE_FILES_DIR => /usr/Kamanja_1.6.0_2.11/input/SampleApplications/metadata/message/
CONFIG_FILES_DIR => /usr/Kamanja_1.6.0_2.11/input/SampleApplications/metadata/config/
MANIFEST_PATH => /usr/Kamanja_1.6.0_2.11/config/manifest.mf
CLASSPATH => /usr/Kamanja_1.6.0_2.11/lib/system/ExtDependencyLibs_2.11-1.6.0.jar:/usr/Kamanja_1.6.0_2.11/lib/system/KamanjaInternalDeps_2.11-1.6.0.jar:/usr/Kamanja_1.6.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.6.0.jar
NOTIFY_ENGINE => YES
NODE_ID => 1
ZNODE_PATH => /kamanja
JAR_TARGET_DIR => /usr/Kamanja_1.6.0_2.11/lib/application
AUDIT_IMPL_CLASS => com.ligadata.audit.adapters.AuditCassandraAdapter
ZK_CONNECTION_TIMEOUT_MS => 3000
METADATA_DATASTORE => {"StoreType": "h2db","connectionMode": "embedded","SchemaName": "kamanja","Location": "/usr/Kamanja_1.6.0_2.11/storage","portnumber": "9100","user": "test","password": "test"}
DO_AUDIT => NO
FUNCTION_FILES_DIR => /usr/Kamanja_1.6.0_2.11/input/SampleApplications/metadata/function/
API_LEADER_SELECTION_ZK_NODE => /ligadata
AUDIT_IMPL_JAR => /usr/Kamanja_1.6.0_2.11/lib/system/auditadapters_2.11-1.0.jar
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/Kamanja_1.6.0_2.11/lib/system/ExtDependencyLibs2_2.11-1.6.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/Kamanja_1.6.0_2.11/lib/system/ExtDependencyLibs_2.11-1.6.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/Kamanja_1.6.0_2.11/lib/system/KamanjaInternalDeps_2.11-1.6.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
Adding the next model in the queue.
ERROR [main] - COMPILER_PROXY: Unable to find at least one message in the Metadata for this model
ERROR [main] - COMPILER_PROXY: unable to determine model metadata information during AddModel.
com.ligadata.Exceptions.MsgCompilationFailedException: kamanja.helloworldmodel`
