### ISSUE TITLE
Serializer/De-serializer for Messages/Containers

### ISSUE THREAD

**Issue by ligadata-saleh** [LigaData/Kamanja#1047]
Hi 
   i tried some of the commands from the Document [](http://kamanja.org/advanced-developers-guide-1-4/serialization-1-4/#Built-in_Kamanja_Serialization_and_Deserialization) but none of them seem to exist for example "./kamanja list serializations" return 
Result: {
  "APIResults" : {
    "Status Code" : -1,
    "Function Name" : "StartMetadataAPI",
    "Result Data" : null,
    "Result Description" : "No value found for 'listserialization'"
  }
}

Thanks
Saleh

**Comment by ligadata-pokuri** [comment]
Alison, We need to have documentation sync.

**Comment by ligadata-rich** [comment]
Currently the serializers currently have no metadata api command support.   That is, one cannot currently add, remove serializers with kamanja commands.   The metadata api serializer related command support will be part of a future sprint (likely 1.5). 

Instead there are three serializers that are provided and currently fixed in the system.  There are:

    ```
    com.ligadata.kamanja.serializer.csvserdeser
    com.ligadata.kamanja.serializer.jsonserdeser
    com.ligadata.kamanja.serializer
```

Alison, I believe we already have some documentation for the three serializers (I am hazy about it... that was a month ago or so when I sent you something).  The main thing is to put the commen about no metadata support and its likely availability at the top of the serializer section in the document.

Ping me if you have questions.

**Comment by ligadata-alison** [comment]
Hi Rich,
    I have fixed the documentation accordingly:

http://kamanja.org/advanced-developers-guide-1-4/serialization-1-4/

Please verify that it is correct.
thanks,
alison

**Comment by ligadata-pokuri** [comment]
Hi Alison

 

We should not have any commands we are not supporting. I still see this. Rich can you take old documentation you provided to Alison and modify and send new documentation to her instead of ask her to remove line by line.

 

§  kamanja <api config properties path> add serialization CONFIG <serialize/deserialize config file path>

§  kamanja <api config properties path> update CONFIG <serialize/deserialize config file path>

§  kamanja <api config properties path> remove serialization NAME <namespace.name>

 

 

Regards,

Sreenivasulu Pokuri

Principal Software Engineer

E: pokuri@ligadata.com  M: 425.233.0960

LD

**Comment by ligadata-pokuri** [comment]
Waiting for rich to update and provide new documentation.

**Comment by ligadata-rich** [comment]
Documentation has been sent to Alison and everyone in the engine group three times ... the last one being the final (afaiac).  Here is a link to the file I sent:

[UsingSerializationAndDeserializationInKamanjaNEW.txt](https://github.com/LigaData/Kamanja/files/239755/UsingSerializationAndDeserializationInKamanjaNEW.txt)

**Comment by ligadata-rich** [comment]
A;ison, Once integrated into the documentation, please close this issue.

**Comment by ligadata-pokuri** [comment]
once documentation is updated assign this to saleh. he will check for the functionality and close. List serializes should return the ones we have.

**Comment by ligadata-rich** [comment]
We have not implemented the list serializers.  Since there is no ability to
add another serializer to the system in this release, the "fix" afaiac is
to document the names in the documentation that Alison posted previously.

If you want a list command, that can be done too.

**Comment by ligadata-pokuri** [comment]
Then once the documentation is updated, saleh will go thru the documentation and close this as invalid bug for 1.4.0.

**Comment by ligadata-saleh** [comment]
verfiyed
