### ISSUE TITLE
Result Description is not correct when running (kamanja dump all functions)

### ISSUE THREAD

**Issue by ligadata-ahmad** [LigaData/Kamanja#1296]
command :

kamanja dump all functions

The current message : "Successfully fetched all containers"
should be replaced with "Successfully fetched all functions"

**Comment by ligadatahari** [comment]
fixed

**Comment by ligadata-william** [comment]
This is still an issue in 1.5.0.Test. Please indicate the branch you checked the fix into.

**Comment by ligadata-william** [comment]
I got the correct branch now :P and this is verified as fixed.
