### ISSUE TITLE
Kamanja commands contain no option for watching the FailedEvents queue

### ISSUE THREAD

**Issue by ligadata-william** [ligaDATA/Kamanja#909]
On branch v13MonitorEnhancements the kamanja script allows for
```
kamanja watch input queue
kamanja watch output queue
kamanja watch status queue
```
However, it doesn't have an option for
```
kamanja watch failed events queue
```
to allow the user easy access to the failed events.

**Comment by ligadata-pokuri** [comment]
Added 
Checked-in changes with commit       https://github.com/ligaDATA/Kamanja/commit/b2d5db23018bd83250b58388bad8043e89115f9e

**Comment by ligadata-william** [comment]
Tested the easy install and I get this error:
```
sed: /private/tmp/Kamanja/template/script/WatchFailedEventQueue_Template: No such file or directory
```
Looks like a .sh is missing form the end?

**Comment by ligadata-pokuri** [comment]
As you said .sh is missing. It is fixed now

**Comment by ligadata-william** [comment]
The script is there now but I still can't run
```
kamanja watch failed events queue
```
We still need that script accessible through kamanja.

**Comment by ligadata-pokuri** [comment]
Added the command in  https://github.com/ligaDATA/Kamanja/pull/918

**Comment by ligadata-william** [comment]
Verified fixed. Closing.
